---
- name: Install Python and related packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev

- name: Install global Python packages
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - virtualenv
      - pipenv
      - pytest
      - flask
      - requests
      - pandas
      - numpy
      - pyodbc

- name: Install UV Virtual Environment
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - uv     