---
- name: Install kubectl
  apt:
    name: kubectl
    state: present

- name: Install Kind
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/kind
    mode: '0755'

- name: Install Helm
  apt:
    name: helm
    state: present