---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential
      - git
      - curl
      - wget
      - unzip
      - htop
      - net-tools
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - zsh